### PR TITLE
fix for bunyan version

### LINKED ISSUE #15: Error: Timestamp is null
Hi there,

I am seeing this error when running in AWS:

```
InvalidParameterException: 1 validation error detected: Value null at 'logEvents.1.member.timestamp' failed to satisfy constraint: Member must not be null
    at Request.extractError (/api/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/api/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/api/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/api/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/api/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/api/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/api/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/api/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/api/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/api/node_modules/aws-sdk/lib/request.js:37:9)
```

I have configured the logger like so:

```
module.exports = function() {

    var bunyan = require('bunyan'),
        Bunyan2Loggly = require('bunyan-loggly').Bunyan2Loggly,
        bformat = require('bunyan-format'),
        formatOut = bformat({ outputMode: 'short' }),
        log
    ;

    if (process.env.NODE_ENV === 'local') {
        log = bunyan.createLogger({'name': 'LOCAL', stream: formatOut});
    } else {
        log = bunyan.createLogger({
            name: process.env.LOGGLY_ALIAS.replace('.%s', ''),
            streams: [
                {
                    level: 'error',
                    type: 'raw',
                    stream: new Bunyan2Loggly({
                        token: process.env.LOGGLY_TOKEN,
                        subdomain: process.env.LOGGLY_SUBDOMAIN
                    })
                },
                {
                    level: 'fatal',
                    type: 'raw',
                    stream: require('bunyan-cloudwatch')({
                        logGroupName: process.env.OPSGENIE_CW_GROUP,
                        logStreamName: 'service-api-ops-cloudwatch-stream',
                        cloudWatchLogsOptions: {
                            accessKeyId: process.env.AWS_KEY,
                            secretAccessKey: process.env.AWS_SECRET,
                            region: process.env.AWS_REGION
                        }
                    })
                }
            ]
        });
    }

    return log;

};

```

Using the logger:

```
log.fatal('TESTING CLOUDWATCH');
```

Thanks

### PR DESCRIPTION
**Pull request by gregorskii**
Fixes #15

### CODE REVIEW

**Comment by gregorskii** [comment]
Hi @mirkokiefer is this build failing due to something I did, or for Travis config?

I have this fork running on my project and it is working fine.

Let me know what I would need to do to get this merged in.

Thanks!

**Comment by focusaurus** [comment]
Also seeing this. Any chance of merging this fix and publishing a new version to npm?

**Comment by mirkokiefer** [comment]
@gregorskii you can see the logs of the failed test in travis:
https://travis-ci.org/mirkokiefer/bunyan-cloudwatch/jobs/109962508

**Comment by gregorskii** [comment]
I'll look into it more. I only changed one line. Is it likely the Bunyan version update may have done it?

**Comment by focusaurus** [comment]
FYI the following combination seems to work OK
- bunyan-cloudwatch  v2.0.0
- bunyan v1.8.0
- Making sure to configure the cloudwatch stream as `raw: true`

**Comment by torgeir** [comment]
Also hit this.

> Making sure to configure the cloudwatch stream as raw: true

This fixed #15 for me.

**Pull request closed without merging**
